version: '3.8'
services:
  database:
    image: mongo:latest
    container_name: mongo-server-golang
    environment:
     MONGO_INITDB_ROOT_USERNAME: 
     MONGO_INITDB_ROOT_PASSWORD: 
    ports:
      - 27017:27017
    volumes:      
      - mongodb_data_container:/data/db  
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: 
      ME_CONFIG_MONGODB_ADMINPASSWORD: 
      ME_CONFIG_MONGODB_SERVER: mongo-server-golang
      ME_CONFIG_MONGODB_PORT: "27017"
    ports:
      - 8081:8081
volumes:
  mongodb_data_container: